
export const secrets: Record<string, string> = {
    NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME!,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL!,
    NEXT_PUBLIC_ICON_URL: process.env.NEXT_PUBLIC_ICON_URL!,
    NEXT_PUBLIC_ONCHAINKIT_API_KEY: process.env.NEXT_PUBLIC_ONCHAINKIT_API_KEY!,
    FARCASTER_HEADER: process.env.FARCASTER_HEADER!,
    FARCASTER_PAYLOAD: process.env.FARCASTER_PAYLOAD!,
    FARCASTER_SIGNATURE: process.env.FARCASTER_SIGNATURE!,
    NEXT_PUBLIC_APP_ICON: process.env.NEXT_PUBLIC_APP_ICON!,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST!,
    RELOADLY_TOP_UP_ACCESS_TOKEN: process.env.RELOADLY_TOP_UP_ACCESS_TOKEN!,
    NODE_ENV: process.env.NODE_ENV!,
    EXCHANGE_RATE_KEY: process.env.EXCHANGE_RATE_KEY!,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY!,
    SELF_APP_SCOPE: process.env.SELF_APP_SCOPE!,
    SELF_API_ENDPOINT: process.env.SELF_API_ENDPOINT!,
    RESEND_API_KEY: process.env.RESEND_API_KEY!,
};
