mutation Orders_CreateSell($input: Order_CreteSellInput!) {
  orders_CreateSell(input: $input) {
    message
  }
}

query Orders_GetAll($input: Order_GetAllInput!) {
  orders_GetAll(input: $input) {
    id
    action_user
    status
    bank_id
    currency_fiat
    status
    trade_type
    action_user
    action_merchant
    amount_crypto
    amount_fiat
  }
}

mutation Orders_CreateBuy($input: Order_CreteBuyInput!) {
  orders_CreateBuy(input: $input) {
    message
  }
}

query orders_GetTransferAccount {
  orders_GetTransferAccount {
   bankName
    accountNo
    accountName
  }
}
# query Orders_GetOne($input: Order_GetOneInput!) {
#   orders_GetOne(input: $input) {
#     id
#     action_user
#     status
#     amount_fiat
#     amount_crypto
#     bank_id
#     amount_crypto
#     currency_fiat
#     estimated_duration
#     merchant_id
#     status
#     trade_type
#     wallet_customer
#     wallet_merchant
#     action_user
#     action_merchant
#     mode
#     txn_hash
#   }
# }

# query Orders_GetAllForAdmin($input: Order_GetAllInput!) {
#   orders_GetAllForAdmin(input: $input) {
#     id
#     action_user
#     status
#     amount_fiat
#     amount_crypto
#     bank_id
#     amount_crypto
#     currency_fiat
#     currency_crypto
#     estimated_duration
#     merchant_id
#     status
#     trade_type
#     wallet_customer
#     wallet_merchant
#     action_user
#     action_merchant
#     mode
#     txn_hash
#   }
# }
