mutation WalletCrypto_create {
  walletCrypto_create {
    address
    chainType
    id
    wallet_id
  }
}

query WalletCrypto_getAll {
  walletCrypto_getAll {
    address
    chainType
    id
    wallet_id
  }
}


mutation WalletCrypto_mobileCreate($input: Wallet_CreateInput!) {
  walletCrypto_mobileCreate(input: $input) {
    message
  }
}
